### ISSUE TITLE
Circle CI Badge is broken

### ISSUE THREAD

**Issue by tonyxiao** [segment-integrations/integration-amplitude#17]
![image](https://cloud.githubusercontent.com/assets/696842/16573893/437df8ac-4279-11e6-828e-b9d04cfb54ec.png)

Also it seems that at some point there's no more tests?

![image](https://cloud.githubusercontent.com/assets/696842/16573901/59c1bb80-4279-11e6-9043-d4780e688f1f.png)

**Comment by f2prateek** [comment]
I think it's because the permissions might not be setup correctly for this repo in Circle.

**Comment by tonyxiao** [comment]
@f2prateek still broken fwiw
